name: core_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dotted_border: ^2.1.0
  dotted_box: ^0.0.3
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_quill: ^10.8.4
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  pick_image: ^1.0.0
  syncfusion_flutter_charts:
    git:
      url: https://github.com/iktakahiro/flutter-widgets.git
      ref: support-flutter-3.24.0
      path: packages/syncfusion_flutter_charts
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.0
  dotted_line: ^3.2.3
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  http_parser: ^4.0.2
  file_picker: ^8.1.3
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  path: ^1.9.0
  path_provider: ^2.1.5
  flutter_pdfview: ^1.3.4
  pdf: ^3.11.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/illustration/
    - assets/logo/
